plugins {
    id 'java'
}

repositories{
    mavenCentral()
}

dependencies{
    implementation "org.jetbrains.kotlin:kotlin-scripting-jsr223:2.3.20"
}

jar{
    archiveFileName = "fooKotlinScriptSupport.jar"
    from configurations.runtimeClasspath.collect{ it.isDirectory() ? it : zipTree(it) }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
